trigger:
  branches:
    include:
    - main
    - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    yarn ci:setup
  displayName: 'Yarn install and build'

- task: npmAuthenticate@0
  inputs:
    customEndpoint: 'NPM connection 1'
    workingFile: .npmrc

- script: |
    yarn ci:prerelease
  displayName: 'Pre-Release if develop'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))

- script: |
    yarn ci:release
  displayName: 'Release if main'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
